version: '3'
services:
  web:
    image: nginx:1.22
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/nginx/certs/
    depends_on:
      - app
    networks:
      - app

  app:
    build: .
    volumes:
      - .:/app
    networks:
      - app

networks:
  app:
